authsys/urls.py
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from .views import login, logout

app_name = 'authsys'
urlpatterns = [
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
] \
		+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
		+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \

magazine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from magazine import views
#from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^product/', include('products.urls')),
    url(r'^auth/', include('authsys.urls')),
    
] \
		+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
		+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \

products/urls.py
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from products import views

app_name = 'products'
urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', views.product_view, name='product-view'),
] \
		+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
		+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \

authsys/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from products.models import Product
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class OrderStatus(models.Model):
	title = models.CharField(max_length=256, blank=True, null=True, default=None)
	description = models.TextField(blank=True, null=True, default=None)

	def __str__(self):
		return '%s' % self.title


class Order(models.Model):
	user = models.ForeignKey(User, blank=True, null=True, default=None)
	create = models.DateTimeField(auto_now_add=False, auto_now=True)
	order_price = models.FloatField(blank=True, null=True, default=None)
	status = models.ForeignKey(OrderStatus, blank=True, null=True, default=None)

	def __str__(self):
		return 'User: %s price: %s status: %s' % (self.user, self.order_price, self.status)



class OrderProduct(models.Model):
	order = models.ForeignKey(Order, blank=True, null=True, default=None)
	product = models.ForeignKey(Product, blank=True, null=True, default=None)
	num = models.IntegerField(blank=True, null=True, default=None)
	price = models.FloatField(blank=True, null=True, default=None)  #product.price
	total_price = models.FloatField(blank=True, null=True, default=None)  #self.product.price * self.num
	is_active = models.BooleanField(default=True)

	
	def save(self, *args, **kwargs):
		self.price = self.product.price
		self.total_price = self.num * self.price

		super(OrderProduct, self).save(*args, **kwargs)


def total_price_post_save(sender, instance, created, **kwargs):
	product_in_order = OrderProduct.objects.filter(order=instance.order, is_active=True)
	total_price = 0
	for item in product_in_order:
		total_price += item.total_price

	instance.order.order_price = total_price
	instance.order.save(force_update=True)

post_save.connect(total_price_post_save, sender=OrderProduct)

products/models.py
from django.db import models
from unidecode import unidecode
from django.template.defaultfilters import slugify


class Category(models.Model):
	title = models.CharField(max_length=50, blank=True, null=True, default=None)
	description = models.TextField(blank=True, null=True, default=None)
	#parent_category = models.ForeignKey(Category, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return '%s' % self.title


class Property(models.Model):
	category = models.ForeignKey(Category, blank=True, null=True, default=None)
	#id_product = models.ForeignKey(Product)
	name = models.CharField(max_length=250, blank=True, null=True, default=None)
	#product = models.ForeignKey()
	is_active = models.BooleanField(default=True)


	def __str__(self):
		return self.name


# Таблиця товарів
class Product(models.Model):
	title = models.CharField(max_length=128, blank=True, null=True, default=None)
	slug = models.SlugField(max_length=128, unique=True, blank=True, default=None, null=True)
	category = models.ForeignKey(Category, blank=True, null=True, default=None)
	description = models.TextField(blank=True, null=True, default=None)
	price = models.FloatField(blank=True, null=True, default=None)
	#product_property = models.ForeignKey(Property, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return '%s' % self.title

	def save(self):
		if not self.slug:
			self.slug = slugify(unidecode(self.title))
		super(Product, self).save()



# Значення характеристик товару
class PropertyValue(models.Model):
	product = models.ForeignKey(Product)
	property = models.ForeignKey(Property)
	value = models.CharField(max_length=100, blank=True, null=True, default=None)
	unit_of_measurement = models.CharField(max_length=16, blank=True, null=True, default=None)

	def __str__(self):
		return '%s' % self.value


# Зображення товарів
class ProductImage(models.Model):
	product = models.ForeignKey(Product, blank=True, null=True, default=None, related_name='images')
	image = models.ImageField(upload_to='products_images/')
	sort_order = models.IntegerField( blank=True, null=True, default=0)
	is_main = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return '%s' % self.id

	class Meta:
		ordering = ['sort_order']

authsys/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import auth


def login(request):

	login_errors = ''
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = auth.authenticate(username=username, password=password)
		if user is not None:
			auth.login(request, user)
			return redirect("/")
		else:
			login_errors = 'User not exist'
			#context = {'login_error': login_error}
			return render(request, 'auth/login.html', {'context': login_errors})
	else:
		return render(request, 'auth/login.html', {'context': login_errors})


def logout(request):
	auth.logout(request)
	return redirect('/')

magazine/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from products.models import ProductImage, Product
#magazine views
def index(request):
	product_images = ProductImage.objects.filter(is_active=True, is_main=True)
	if request.user.is_authenticated:
		username = request.user.username

	return render(request, 'magazine/home.html', locals())

def slider(request):
	images = ProductImage.objects.filter(product=1).order_by('is_main')
	main = ProductImage.objects.get(product=1, is_main=True)

	return render(request, 'slider.html', locals())

order/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import ProductImage, PropertyValue, Product

def product_view(request, slug):
	product = get_object_or_404(Product, slug=slug)
	image = ProductImage.objects.get(product=product.id, is_main=True)
	# product_images = ProductImage.objects.filter(product_id=product.id)
	
	# main = ProductImage.objects.get(product=product.id, is_main=True)

	propertys = PropertyValue.objects.filter(product=product.id)

	if request.user.is_authenticated:
		username = request.user.username
	
	return render(request, 'products/product_page.html', locals())

templates/django/app/login.html
<html>
	<head><title>login</title></head>
	
		
	<body>
		<form method="POST" action="{% url 'authsys:login' %}">{% csrf_token %}
			{% if context %}
			<a style="color:red;">{{ context }}</a>
			{% endif %}
			<label>Username</label>
			<input type="text" name="username">
			<label>Password</label>
			<input type="password" name="password">
			<input type="submit" value="login">
		</form>
	</body>
</html>

templates/django/app/main.html
<html>
	<head><title>login</title></head>
	
		
	<body>
		{% if username %}
		<h4>Hello {{ username }} </h4><a href="{% url 'logout' %}">Logout</a>
		{% else %}
		<form method="POST" action="{% url 'login' %}">{% csrf_token %}
			{% if context %}
			<a style="color:red;">{{ context }}</a>
			{% endif %}
			<label>Username</label>
			<input type="text" name="username">
			<label>Password</label>
			<input type="password" name="password">
			<input type="submit" value="login">
		</form>
		{% endif %}
		<p>Wellcome to our web site!!!</p>
	</body>
</html>

templates/django/base.html
{% load static %}
<html>
	<head>
		<title>Magazine</title>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">

 		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 		<!-- <script src="{% static 'slider.js' %}"></script> -->
 		<!-- <script src="{% static 'login.js' %}"></script> -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>

	<body>
		
		{% include 'navbar.html' %}

		{% block content %}{% endblock %}
		
		{% include 'footer.html' %}
		
	</body>

</html>

templates/django/footer.html
<footer>
	<div class="text">
		<h3>FOOTER</h3>
	</div>
</footer>

templates/django/magazine/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="section">
		<div class="container">
			<div class="row">
				{% for product_image in product_images %}
					<div class="product-wrapper">
						<div class="product-item">
							<div class="product-photo">
								<a href="{% url 'products:product-view' product_image.product.slug %}"><img src="{{ product_image.image.url }}"></a>
							</div>
							<div class="product-title">
								<h4><a href="{% url 'products:product-view' product_image.product.slug %}">{{ product_image.product.title }}</a></h4>
							</div>
							<p>
								{{ product_image.product.description| truncatechars:70 }}
							</p>
							<div class="add-to-cart-btn">
								<button class="btn btn-success">
									Add to cart
								</button>
							</div>
							<div class="product-price">
								{{ product_image.product.price }} UAH
							</div>

						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/django/modal_form.html
<!-- BEGIN # MODAL LOGIN -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" align="center">
        <img class="img-circle" id="img_logo" src="http://bootsnipp.com/img/logo.jpg">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </button>
      </div>

      <!-- Begin # DIV Form -->
      <div id="div-forms">

      <!-- Begin # Login Form -->
        <form id="login-form">
          <div class="modal-body">
            <div id="div-login-msg">
              <div id="icon-login-msg" class="glyphicon glyphicon-chevron-right"></div>
              <span id="text-login-msg">Type your username and password.</span>
            </div>
            <input id="login_username" class="form-control" type="text" placeholder="Username (type ERROR for error effect)" required>
            <input id="login_password" class="form-control" type="password" placeholder="Password" required>
            <div class="checkbox">
              <label>
              <input type="checkbox"> Remember me
              </label>
            </div>
          </div>
          <div class="modal-footer">
            <div>
              <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
            </div>
            <div>
              <button id="login_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
              <button id="login_register_btn" type="button" class="btn btn-link">Register</button>
            </div>
          </div>
        </form>
                <!-- End # Login Form -->
                
      <!-- Begin | Lost Password Form -->
      <form id="lost-form" style="display:none;">
        <div class="modal-body">
          <div id="div-lost-msg">
            <div id="icon-lost-msg" class="glyphicon glyphicon-chevron-right"></div>
              <span id="text-lost-msg">Type your e-mail.</span>
            </div>
            <input id="lost_email" class="form-control" type="text" placeholder="E-Mail (type ERROR for error effect)" required>
        </div>
        <div class="modal-footer">
          <div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Send</button>
          </div>
          <div>
            <button id="lost_login_btn" type="button" class="btn btn-link">Log In</button>
            <button id="lost_register_btn" type="button" class="btn btn-link">Register</button>
          </div>
        </div>
      </form>
      <!-- End | Lost Password Form -->
                
      <!-- Begin | Register Form -->
      <form id="register-form" style="display:none;">
        <div class="modal-body">
          <div id="div-register-msg">
            <div id="icon-register-msg" class="glyphicon glyphicon-chevron-right"></div>
            <span id="text-register-msg">Register an account.</span>
          </div>
          <input id="register_username" class="form-control" type="text" placeholder="Username (type ERROR for error effect)" required>
          <input id="register_email" class="form-control" type="text" placeholder="E-Mail" required>
          <input id="register_password" class="form-control" type="password" placeholder="Password" required>
        </div>
        <div class="modal-footer">
          <div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Register</button>
          </div>
          <div>
            <button id="register_login_btn" type="button" class="btn btn-link">Log In</button>
            <button id="register_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
          </div>
        </div>
      </form>
    <!-- End | Register Form -->
              
    </div>
    <!-- End # DIV Form -->

    </div>
  </div>
</div>
    <!-- END # MODAL LOGIN -->

templates/django/navbar.html
<nav class="navbar navbar-default navbar-main">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Duploma</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
            <!-- <div class="basket-container">
                <a href="">Корзина <span id="basket_total_amount"></span><span id="basket_total_nmb"></span></a>
                <div class="basket-items hidden">
                    <ul class="">
                        {% for product_in_basket in products_in_basket %}
                            <li>
                                {{ product_in_basket.product.name }} {{ product_in_basket.nmb }} шт.
                                по {{ product_in_basket.price_per_item }} грн.
                                <a class="delete-item" href="" data-product_id="{{ product_in_basket.id }}">x</a>
                            </li>
                        {% endfor %}
                        <li>
                            <a href="#">
                                Оформить заказ
                            </a>
                        </li>
                    </ul>
                </div>
            </div> -->
        <li><a href="#"><span class="glyphicon glyphicon-heart"></span>Wish list</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-tree-conifer"></span>Compare</a></li>
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> -->
        {% if username %}
        <li><a href="{% url 'authsys:logout' %}" role="button"><span class="glyphicon glyphicon-log-in"></span>Logout ({{ username }})</a></li>
        {% else %}
        <li><a href="{% url 'authsys:login' %}" role="button"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/django/products/product_page.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ product.title }}</h1>

<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<div class="product-image">
				<img src="{{ image.image.url}}">
			</div>
		</div>

		<div class="col-lg-6">
			<div class="product-col">
				<div class="description">
					<h3>Description</h3>
					<p>{{ product.description }}<p>
				</div>
				<div class="add-to-cart">
					<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span>Buy</button>

					<button type="button" class="btn btn-light"><span class="glyphicon glyphicon-heart"></span>Add to wish list</button>
					<button type="button" class="btn btn-light"><span class="glyphicon glyphicon-tree-conifer"></span>Compare</button>
				</div>
			</div>
		</div>
	</div>
</div>



{#<!-- Product propertys -->
{% for property in propertys %}
<p>{{ property.property.name }}: {{ property.value}}{{ property.unit_of_measurement}}
{% endfor %}
#}
{% endblock %}

templates/django/slider.html
{% extends 'base.html' %}

{% block content %}
<div class="slider-wrapper">
	<div class="prew-img">
	{% for image in images %}
		<div class="img-thumbs">
			<a href="#"><img src="{{ image.image.url }}" alt="" class="img-responsive"  onmouseover="onHover(this.id)" id="{{ image.image.url }}"></a>
		</div>
	{% endfor %}
	</div>
	<div class="full-img">
		<img src="{{ main.image.url }}" id="productImage">
	</div>
	<div class="clearfix"></div>
</div>

<div class="clearfix"></div>

{% endblock %}

templates/django/user_name.html
{% extends 'base.html' %}

{% block content %}
	<h1>Your name: {{ username }} </h1>
{% endblock %}

templates/jinja2/base.html
<html>
	<head>
		<title>Magazine</title>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="{{ static('style.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ static('login.css') }}">

 		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 		<script src="{{ static('slider.js') }}"></script>
 		<script src="{{ static('login.js') }}"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>

	<body>
		
		{% include 'navbar.html' %}

		{% block content %}{% endblock %}
		{% block login %}{% endblock %}

		{% include 'footer.html' %}
		
	</body>

</html>

templates/jinja2/footer.html
<footer>
	<div class="text">
		<h3>FOOTER</h3>
	</div>
</footer>

templates/jinja2/magazine/home.html
{% extends './base.html' %}

{% block content %}
	<div class="section">
		<div class="container">
			<div class="row">
				{% for product_image in product_images %}
					<div class="product-wrapper">
						<div class="product-item">
							<div class="product-photo">
								<a href="{{ url('products:product-view', args=[product_image.product.slug]) }}"><img src="{{ product_image.image.url }}"></a>
							</div>
							<div class="product-title">
								<h4><a href="{{ url('products:product-view', args=[product_image.product.slug]) }}">{{ product_image.product.title }}</a></h4>
							</div>
							<p>
								{{ product_image.product.description| truncate(70) }}
							</p>
							<div class="add-to-cart-btn">
								<button class="btn btn-success">
									Add to cart
								</button>
							</div>
							<div class="product-price">
								{{ product_image.product.price }} UAH
							</div>

						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

templates/jinja2/navbar.html
<nav class="navbar navbar-default navbar-main">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Duploma</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a></li>
           <!--  <div class="basket-container">
                <a href="">Корзина <span id="basket_total_amount"></span><span id="basket_total_nmb"></span></a>
                <div class="basket-items hidden">
                    <ul class="">
                        {% for product_in_basket in products_in_basket %}
                            <li>
                                {{ product_in_basket.product.name }} {{ product_in_basket.nmb }} шт.
                                по {{ product_in_basket.price_per_item }} грн.
                                <a class="delete-item" href="" data-product_id="{{ product_in_basket.id }}">x</a>
                            </li>
                        {% endfor %}
                        <li>
                            <a href="#">
                                Оформить заказ
                            </a>
                        </li>
                    </ul>
                </div>
            </div> -->
        <li><a href="#"><span class="glyphicon glyphicon-heart"></span>Wish list</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-tree-conifer"></span>Compare</a></li>
        <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> -->
        {% if username %}
        <li><a href="#" role="button"><span class="glyphicon glyphicon-log-in"></span>Logout ({{ username }})</a></li>
        {% else %}
        <li><a href="{{ url('authsys:login') }}" role="button"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>


<!-- BEGIN # MODAL LOGIN -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" align="center">
        <img class="img-circle" id="img_logo" src="http://bootsnipp.com/img/logo.jpg">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </button>
      </div>

      <!-- Begin # DIV Form -->
      <div id="div-forms">

      <!-- Begin # Login Form -->
        <form id="login-form">
          <div class="modal-body">
            <div id="div-login-msg">
              <div id="icon-login-msg" class="glyphicon glyphicon-chevron-right"></div>
              <span id="text-login-msg">Type your username and password.</span>
            </div>
            <input id="login_username" class="form-control" type="text" placeholder="Username (type ERROR for error effect)" required>
            <input id="login_password" class="form-control" type="password" placeholder="Password" required>
            <div class="checkbox">
              <label>
              <input type="checkbox"> Remember me
              </label>
            </div>
          </div>
          <div class="modal-footer">
            <div>
              <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
            </div>
            <div>
              <button id="login_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
              <button id="login_register_btn" type="button" class="btn btn-link">Register</button>
            </div>
          </div>
        </form>
                <!-- End # Login Form -->
                
      <!-- Begin | Lost Password Form -->
      <form id="lost-form" style="display:none;">
        <div class="modal-body">
          <div id="div-lost-msg">
            <div id="icon-lost-msg" class="glyphicon glyphicon-chevron-right"></div>
              <span id="text-lost-msg">Type your e-mail.</span>
            </div>
            <input id="lost_email" class="form-control" type="text" placeholder="E-Mail (type ERROR for error effect)" required>
        </div>
        <div class="modal-footer">
          <div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Send</button>
          </div>
          <div>
            <button id="lost_login_btn" type="button" class="btn btn-link">Log In</button>
            <button id="lost_register_btn" type="button" class="btn btn-link">Register</button>
          </div>
        </div>
      </form>
      <!-- End | Lost Password Form -->
                
      <!-- Begin | Register Form -->
      <form id="register-form" style="display:none;">
        <div class="modal-body">
          <div id="div-register-msg">
            <div id="icon-register-msg" class="glyphicon glyphicon-chevron-right"></div>
            <span id="text-register-msg">Register an account.</span>
          </div>
          <input id="register_username" class="form-control" type="text" placeholder="Username (type ERROR for error effect)" required>
          <input id="register_email" class="form-control" type="text" placeholder="E-Mail" required>
          <input id="register_password" class="form-control" type="password" placeholder="Password" required>
        </div>
        <div class="modal-footer">
          <div>
            <button type="submit" class="btn btn-primary btn-lg btn-block">Register</button>
          </div>
          <div>
            <button id="register_login_btn" type="button" class="btn btn-link">Log In</button>
            <button id="register_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
          </div>
        </div>
      </form>
    <!-- End | Register Form -->
              
    </div>
    <!-- End # DIV Form -->

    </div>
  </div>
</div>
    <!-- END # MODAL LOGIN -->

templates/jinja2/products/product_page.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ product.title }}</h1>

<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<div class="product-image">
				<img src="{{ image.image.url}}">
			</div>
		</div>

		<div class="col-lg-6">
			<div class="product-col">
				<div class="description">
					<h3>Description</h3>
					<p>{{ product.description }}<p>
				</div>
				<div class="add-to-cart">
					<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-shopping-cart"></span>Buy</button>

					<button type="button" class="btn btn-light"><span class="glyphicon glyphicon-heart"></span>Add to wish list</button>
					<button type="button" class="btn btn-light"><span class="glyphicon glyphicon-tree-conifer"></span>Compare</button>
				</div>
			</div>
		</div>
	</div>
</div>



{#<!-- Product propertys -->
{% for property in propertys %}
<p>{{ property.property.name }}: {{ property.value}}{{ property.unit_of_measurement}}
{% endfor %}
#}
{% endblock %}

templates/jinja2/slider.html
{% extends 'base.html' %}

{% block content %}
<div class="slider-wrapper">
	<div class="prew-img">
	{% for image in images %}
		<div class="img-thumbs">
			<a href="#"><img src="{{ image.image.url }}" alt="" class="img-responsive"  onmouseover="onHover(this.id)" id="{{ image.image.url }}"></a>
		</div>
	{% endfor %}
	</div>
	<div class="full-img">
		<img src="{{ main.image.url }}" id="productImage">
	</div>
	<div class="clearfix"></div>
</div>

<div class="clearfix"></div>

{% endblock %}

templates/jinja2/user_name.html
{% extends 'base.html' %}

{% block content %}
	<h1>Your name: {{ username }} </h1>
{% endblock %}